--create procedure cargarRuta(
--	@id_archivo int,
--	@ruta varchar(255),
--	@id_revisionlevel int,
--	@md5 varchar(255))
--as
--begin
--	insert into rutas
--	values(@id_archivo, @ruta, @id_revisionlevel, @md5)
--end
