--create procedure createBundle(
--	@descriptores varchar(255),
--	@descriptoren varchar(255),
--	@oemsku varchar(255),
--	@descriptorextra varchar(255),
--	@strextension varchar(255),
--	@strtipoentregable varchar(255),
--	@strproyecto varchar(255))
--as
--begin
--	declare @idproyecto int
--	declare @idtipoentregable int
--	declare @idextension int
--	declare @idarchivos int

--	SET NOCOUNT ON;
--	BEGIN TRANSACTION REGISTRO;
--	begin try
--	/* Obtener id del proyecto*/
--	select @idproyecto=id
--	from proyectos
--	where descriptores like @strproyecto
--	/*Obtener la id de la extension*/
--	select @idextension=id
--	from extensiones
--	where @strextension like '%'+extension+'%'
--	/*Obtener la id del tipo entregable*/
--	select @idtipoentregable=id
--	from tipos_entregables
--	where @strtipoentregable like '%'+nombre+'%'
--	/*insertar file properties*/
--	insert into archivos
--	VALUES(@descriptores, @descriptoren, @oemsku, @idextension, @descriptorextra)
--	set @idarchivos=SCOPE_IDENTITY();
--	select @idarchivos
--	/*insertar file property associations*/
--	insert into entregables
--	values
--		(@idarchivos, @idproyecto, @idtipoentregable)
--	COMMIT TRANSACTION REGISTRO
--END TRY
--BEGIN CATCH
--	ROLLBACK TRANSACTION REGISTRO;
--END CATCH
--	set nocount off
--end
