--create procedure execAgregarUsuario(@userlogin varchar(60),
--	@nombre varchar(60),
--	@apellidos varchar(60),
--	@pass varchar(60))
--as
--begin
--	insert into usuarios
--	values(@userlogin, @nombre, @apellidos, @pass)
--end
