--create procedure execEliminarUsuario(@userlogin varchar(60))
--as
--begin
--	/*Borrar desde userdirs primero*/
--	declare @userid int;
--	/*Obtener id del usuario desde el login*/
--	select @userid=id
--	from usuarios
--	where userlogin=@userlogin
--	/*Borrar del userdirs primero, para evitar conflicto de FK's*/
--	if (select count(*)
--	from userdirs
--	where id_usuario=@userid)>0
--    begin
--		delete from userdirs where id_usuario=@userid
--	end
--	/*Borrar ahora si el usuario*/
--	delete from usuarios where id=@userid
--end
