--create procedure getBundle(@id INT)
--as
--begin
--	select
--		archivos.descriptores as "DescriptorES",
--		archivos.descriptoren as "DescriptorEN",
--		archivos.oemsku as "OEMSKU",
--		archivos.descriptorextra as "DescriptorEXTRA",
--		extensiones.extension as "Extension",
--		extensiones.id as "id Extension",
--		proyectos.descriptores as "Descripcion Proyecto",
--		tipos_entregables.abreviatura as "Tipo Entregable",
--		tipos_entregables.id as "id Tipo Entregable",
--		proyectos.id as "id Proyecto"
--	from archivos, entregables, proyectos, extensiones, tipos_entregables
--	where entregables.id_proyecto=proyectos.id and entregables.id_archivo=archivos.id and archivos.id=@id and archivos.id_extension=extensiones.id and tipos_entregables.id=entregables.id_tipo
--end;
