--create procedure insertFileProjectAssociations(
--	@idarchivo varchar(255),
--	@idproyecto varchar(255),
--	@idtipo varchar(255))
--as
--begin
--	insert into entregables
--	values
--		(@idarchivo, @idproyecto, @idtipo)
--end
