--create procedure obtenerRutaDesdeId(
----	@id_archivo int,
----	@id_revisionlevel int)
----as
----begin
----	select id_archivo, ruta, id_revisionlevel, md5
----	from rutas
----	where id_revisionlevel=@id_revisionlevel and id_archivo=@id_archivo
----end
