CREATE TABLE [dbo].[relaciones]
(
	[ID_RELACION] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [ID_PADRE] INT NOT NULL, 
    [ID_HIJO] INT NOT NULL, 
    CONSTRAINT [FK_RELACIONES_PADRE] FOREIGN KEY ([ID_PADRE]) REFERENCES [directorios]([id_directorio]),
    CONSTRAINT [FK_RELACIONES_HIJO] FOREIGN KEY ([ID_HIJO]) REFERENCES [directorios]([id_directorio])
)
