CREATE TABLE [dbo].[revisionlevels] (
    [ID_REVISIONLEVEL]       INT         IDENTITY (1, 1) NOT NULL,
    [CHAR_REVISIONLEVEL] VARCHAR (2) NOT NULL,
    PRIMARY KEY CLUSTERED ([ID_REVISIONLEVEL] ASC)
);

