CREATE LOGIN [SWPDM]
    WITH PASSWORD = N'rzek{atncuC{m&nkt|8wdpm|msFT7_&#$!~<{vsgmi#nM|bf', SID = 0xEF5EE87241A07D42BEB0E44C817F0ADD, DEFAULT_DATABASE = [FILEIDSLOCAL], DEFAULT_LANGUAGE = [us_english];

